version: '3.8'

services:
  fastapi_server:
    platform: linux/amd64  # Specify platform here
    container_name: fastapi_server
    build: ./backend
    restart: always
    # command: "sh -c 'alembic upgrade head && python app/document_ingestion.py  && uvicorn app.main:app --reload --workers 1 --host 0.0.0.0 --port 9090'"
    # Enable debug mode run .vscode/launch.json -> "Debug: Attach to FastAPI Docker"
    command: "sh -c 'pip install debugpy -t /tmp && alembic upgrade head && python /tmp/debugpy --wait-for-client --listen 0.0.0.0:5678 -m uvicorn app.main:app --reload --workers 1 --host 0.0.0.0 --port 9090 --loop asyncio'"
    ports:
      - 5678:5678
    # Disable debug mode if only frontend development
    volumes:
      - ./backend/app:/code
    expose:
      - 9090
    env_file: ".env"
    depends_on:
      - database


  nextjs_server:
    platform: linux/amd64  # Specify platform here
    container_name: nextjs_server
    build: ./frontend
    restart: always
    # command: "sh -c 'node server.js'"
    command: "node --inspect=0.0.0.0:9229 -r ts-node/register server.js"
    volumes:
      - ./frontend:/code
    ports:
      - 3000:3000
      - 9229:9229
    expose:
      - 3000
    env_file: "frontend/.env"
    depends_on:
      - fastapi_server


  database:
    platform: linux/amd64  # Specify platform here
    image: ankane/pgvector:v0.4.1
    restart: always
    container_name: database
    env_file: ".env"
    user: root
    volumes:
      - ./db_docker:/var/lib/postgresql
      - ./scripts/1-create-dbs.sql:/docker-entrypoint-initdb.d/1-create-dbs.sql
    ports:
      - 5432:5432
    expose:
      - 5432
    environment:
      - POSTGRES_USERNAME=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_DATABASE=${DATABASE_NAME}
      - POSTGRES_HOST_AUTH_METHOD= "trust"

  redis_server:
    platform: linux/amd64  # Specify platform here
    image: redis:alpine
    container_name: redis_server
    restart: always
    ports:
      - 6379:6379 # Remove this on production
    expose:
      - 6379
    env_file: .env

  caddy_reverse_proxy:
    platform: linux/amd64  # Specify platform here
    container_name: caddy_reverse_proxy
    image: caddy:alpine
    restart: always
    ports:
      - 80:80
      - 9090:9090
      - 443:443
    environment:
      - EXT_ENDPOINT1=${EXT_ENDPOINT1}
      - LOCAL_1=${LOCAL_1}
      - LOCAL_2=${LOCAL_2}
    volumes:
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config

  pre-commit:
    build: ./pre-commit
    profiles: ["pre-commit"]
    entrypoint: "pre-commit run"
    volumes:
      - ./backend:/code/backend
      - ./frontend:/code/frontend
      - ./.git:/code/.git
    working_dir: /code

volumes:
  caddy_data:
  caddy_config:
  langchain-db-data:
  langchain-redis-data:
